services:
  postgres:
    image: postgres:17-alpine
    container_name: valyent_ai_postgres
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: valyent_ai
      POSTGRES_PASSWORD: valyent_ai
      POSTGRES_DB: valyent_ai
    volumes:
      - valyent_ai_postgres_data:/var/lib/postgresql/data
    restart: always

volumes:
  valyent_ai_postgres_data:
